export const ICON = Object.freeze({
    info: 'ℹ️',
    settings: '⚙️',
    object: '🧩',
    link: '🔗',
    device: '🔌',
    group: '🏠',
    folder: '📁',
    folderOpen: '📂',
    topology: '🌿',
    area: '🌐',
    line: '〰️',
    building: '🏢',
    tag: '🏷️',
    file: '📄',
    chevronDown: '▼',
    chevronRight: '▶',
    chevronLeft: '◀',
    chevronUp: '▲',
    fullscreen: '⛶',
    fullscreenExit: '🗗',
    buildingFloor: '🧱',
    buildingRoom: '🚪',
    buildingCorridor: '🧭',
    buildingStair: '🪜',
    buildingFunction: '🔧',
    buildingSite: '🏗️'
});
